public with sharing class TestForestListModel {
    public TestForestListModel() {

    }

    /** Report Name */
    @AuraEnabled public String reportName {get; set;}
    /** Report NO  */
    @AuraEnabled public String reportNo {get; set;}
    /** ITEM1 */
    @AuraEnabled public String item1 {get; set;}
    /** ITEM2 */
    @AuraEnabled public String item2 {get; set;}
    /** ITEM3 */
    @AuraEnabled public String item3 {get; set;}
    /** ITEM4 */
    @AuraEnabled public String item4 {get; set;}
    /** ITEM5 */
    @AuraEnabled public String item5 {get; set;}
    /** ITEM6 */
    @AuraEnabled public String item6 {get; set;}



}